DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS venue;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS date;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS listing;
DROP TABLE IF EXISTS sales;
